# Generated by Django 3.2.7 on 2022-05-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_diet', '0002_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
    ]
